learning_templates/basicapp/urls.py
from django.urls import path
from basicapp import views

#for template tagging
app_name = 'basicapp'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/',include('basicapp.urls'))

]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

learning_templates/basicapp/templates/basicapp/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
              <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
              <a class="nav-item nav-link" href="{%url 'admin:index'%}">Admin</a>
              <a class="nav-item nav-link" href="{% url 'basicapp:other' %}">Other</a>
      </div>
  </nav>

  <div class="container">
      {% block body_block %}
      <!--Anything outside of this will be inherited if you extend!-->
      {% endblock %}
  </div>
</body>
</html>

learning_templates/basicapp/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load my_extras %}
  {% block body_block %}
  <h1>WELCOME TO INDEX</h1>
  <!--<h1>This is index.html page showing</h1>-->
  <h1>{{text|cutout:"world"}}</h1>
  <h1>{{number|add:"99"}}</h1>
  {% endblock %}

learning_templates/basicapp/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
  {% block body_block %}
  <h1>WELCOME TO OTHER</h1>
  <h2>This is an example of template inheritance</h2>
  {% endblock %}

learning_templates/basicapp/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
  <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
  <a href="{% url 'admin:index' %}">Link to admin</a>
  <a href ='{% url 'index' %}'> Link to index</a>
</body>
</html>